### ISSUE TITLE
Error getting `belongsTo` relationships

### ISSUE THREAD

**Issue by edalzell** [duncanmcclean/runway#187]
### Description

Getting an error when I'm trying to save a relationship in a stack.

This was introduced in 2.5, to resolve, I've rolled back to 2.4.3

<img width="787" alt="CleanShot 2022-12-06 at 15 29 50@2x" src="https://user-images.githubusercontent.com/6069653/206047748-1feed2c0-3ba8-4d06-ae81-1ed6d086af5b.png">

### Steps to reproduce

Relationship blueprint

```
title: 'Orphan Update'
sections:
  main:
    display: Main
    fields:
      -
        handle: text
        field:
          antlers: false
          display: Update Message
          type: textarea
          icon: textarea
          listable: true
          validate:
            - required
      -
        handle: orphan_id
        field:
          max_items: 1
          mode: select
          title_format: '{{ first_name }} {{ last_name }} ({{ orphan_id }})'
          resource: orphan
          display: Orphan
          type: belongs_to
          icon: belongs_to
          listable: true
      -
        handle: approved
        field:
          default: false
          display: Approved
          type: toggle
          icon: toggle
          listable: true
      -
        handle: attachments
        field:
          mode: list
          container: private
          folder: sponsor-an-orphan/updates
          restrict: true
          allow_uploads: true
          show_filename: true
          display: Attachments
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
```

Stack trace:

```
[2022-12-06 15:00:54] local.ERROR: Call to undefined method App\Models\OrphanUpdate::orphan_id() {"userId":"cba0aed3-26f9-4ca9-a67f-8261a605d37b","exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\OrphanUpdate::orphan_id() at /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
#0 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('orphan_id')
#1 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2321): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'orphan_id', Array)
#2 /Users/erin/Sites/zakat/vendor/doublethreedigital/runway/src/Http/Controllers/ResourceController.php(225): Illuminate\\Database\\Eloquent\\Model->__call('orphan_id', Array)
#3 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): DoubleThreeDigital\\Runway\\Http\\Controllers\\ResourceController->DoubleThreeDigital\\Runway\\Http\\Controllers\\{closure}(Object(Statamic\\Fields\\Field), 'orphan_id')
#4 /Users/erin/Sites/zakat/vendor/doublethreedigital/runway/src/Http/Controllers/ResourceController.php(238): Illuminate\\Support\\Collection->each(Object(Closure))
```

### Environment

```
Environment
Application Name: Statamic
Laravel Version: 9.42.0
PHP Version: 8.1.13
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 19
Antlers: runtime
Version: 3.3.58 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
aryehraber/statamic-impersonator: 2.4.1
doublethreedigital/duplicator: 2.3.4
doublethreedigital/runway: 2.4.3
edalzell/forma: 1.2
jacksleight/statamic-bard-mutator: 1.1.2
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-livewire: 2.9.0
statamic/seo-pro: 3.1.1
swiftmade/statamic-clear-assets: 1.1.0
transformstudios/events: 4.0.7
transformstudios/front: 1.11.0
transformstudios/gated: dev-main
transformstudios/github: dev-main
transformstudios/magic-link: dev-main
transformstudios/memorial: dev-fix/orphan-update-saving
transformstudios/review: 3.7.0
transformstudios/simple: 2.14.1
transformstudios/takeover-redirects: dev-main
```
