### ISSUE TITLE
Runway potentially ignoring visibility: computed

### ISSUE THREAD

**Issue by stoffelio** [duncanmcclean/runway#222]
### Description

In my order blueprint used with SimpleCommerce (via Runway) I have this field:

```
handle: full_address
field:
  antlers: false
  display: 'Full Address'
  type: textarea
  icon: textarea
  listable: hidden
  instructions_position: above
  visibility: computed
  always_save: false
  read_only: true
```

When trying to save the order in the backend, I get the following error message: 

`[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_address' in 'field list' at /home/forge/shop-staging.site.de/vendor/laravel/framework/src/Illuminate/Database/Connection.php:566)`

It looks like Runway is trying to store the field despite `visibility: computed`

### Steps to reproduce

I can provide the full blueprint if you need it to reproduce the issue. The computed value is created on a CustomOrderModel.

### Environment

Environment
Application Name: [Staging] Shop
Laravel Version: 9.51.0
PHP Version: 8.2.1
Composer Version: 2.5.4
Environment: development
Debug Mode: ENABLED
URL: staging.site.de
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standardversand - 3-4 Werktage, Einschreiben Einwurf - 3-4 Werktage, Expressversand - bis zu 48h, Kurier (nur Berlin) - am selben Tag
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 2
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 PRO

Statamic Addons
doublethreedigital/runway: 2.6.7
doublethreedigital/simple-commerce: 4.5.3
