### ISSUE TITLE
Runway shouldn't attempt to save appended attributes

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/runway#240]
### Description

I have an appended attribute on my model for excerpts. 

Whenever I try to save the model, I get an error that the column `excerpt` is not found. This is because Runway is trying to update the column of an appended attribute. We should be checking if it's an appended attribute and if it is, not trying to persist it in the database.

### Field

```yaml
      -
        handle: excerpt
        field:
          antlers: false
          display: Excerpt
          type: text
          icon: text
          listable: true
          instructions_position: above
          visibility: hidden
```

### Eloquent model

```php
protected $appends = [
    'excerpt',
];

public function excerpt(): Attribute
{
    return new Attribute(
        get: fn () => Str::limit($this->original_text, 150, '...'),
    );
}
```

### Steps to reproduce

1 . Add an appended attribute to a model
2. Try to save the model with Runway
3. See it fail

### Environment

Environment
Application Name: Site Name
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: sitename.com.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: USD
Gateways: Stripe, PayPal
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
doublethreedigital/runway: 4.2.2
doublethreedigital/simple-commerce: 4.5.9
jezzdk/statamic-wp-import: 1.6.0
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.27
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 1.1
