### ISSUE TITLE
Unable to see or list models after saving as "title" is not present in the blueprint

### ISSUE THREAD

**Issue by mwilkinson5874** [duncanmcclean/runway#273]
### Description

I have a model which doesn't require the "title" field however when I attempt to save a new record I'm getting the error "Undefined array index 0" which seems to be related to `DoubleThreeDigital\Runway\Resource:220` where you're trying to fetch a title field. The model does save to the database, however I'm unable to see this model in detail or load the corresponding list page. It seems that a title field is expected but in my case I don't want to or have any requirement to have a title column on my model.

I have tried adding in a title field and making it not visible and not required, but this then attempts to add a title column to the insert query and I get a separate error for a column that doesn't exist.

### Steps to reproduce

Model:

```
class Author extends Model
{
    use HasFactory, HasUuids, HasRunwayResource;

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
    ];
}
```

Blueprint:

```
title: Authors
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          # -
          #   handle: title
          #   field:
          #     type: text
          #     required: true
          #     validate:
          #       - required
          -
            handle: first_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'First Name'
              icon: text
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              duplicate: false
              hide_display: false
              validate:
                - required
          -
            handle: last_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Last Name'
              icon: text
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              duplicate: false
              hide_display: false
              validate:
                - required
          -
            handle: email
            field:
              input_type: email
              character_limit: 255
              antlers: false
              type: text
              display: Email
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              duplicate: false
              hide_display: false
              validate:
                - required
                - email
                - 'max:255'
```

Runway resource config:

```
'resources' => [
    \App\Models\Author::class => [
        'name' => 'Authors',
        'blueprint' => 'author',
    ],
],
```

### Environment

```
Environment
Application Name: Example
Laravel Version: 10.10.0
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.1 PRO

Statamic Addons
doublethreedigital/runway: 5.0.4
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.0
studio1902/statamic-peak-tools: 3.2
```

**Comment by duncanmcclean** [comment]
Do you still get the error if you make the `first_name` field listable, eg:

```yaml
# Instead of this...
listable: hidden

# Have it like this...
listable: true
```

You need at least one 'listable column' for the listing table & the top of the publish form page as the page title.
