### ISSUE TITLE
Many to Many pivot table sort_order not updating

### ISSUE THREAD

**Issue by tom-sk** [duncanmcclean/runway#287]
### Description

I am trying to build a LMS with Modules and Topics and want to create a Many to Many relationship where a Modules can have many Topics and a Topic can be assigned to many Modules.

I have 3 tables:
modules
topics
module_topic

When I add the hasMany field type to the Modules table I am able to create and link topics and the module_topics table is updated correctly.

However the sort_order column is not updated. 

I can update it in the DB manually and that will effect the order on the front end.

### Steps to reproduce

1. Create 2 Models
2. Add hasMany field to both
3. create pivot table in DB
4. Add one model to another
5. sort_order not updating in DB

### Environment

Environment
Application Name: Statamic
Laravel Version: 10.13.2
PHP Version: 8.2.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 Solo

Statamic Addons
doublethreedigital/runway: 5.0.7
example/my-addon: dev-master

**Comment by duncanmcclean** [comment]
Can you provide the HasMany fields from your blueprints please?

**Comment by tom-sk** [comment]
Here is the link to the repo I am working on: https://github.com/tom-sk/laravel-lms

I was messing around trying to use `order_column: module_topic.sort_order` in the Modules blueprint

Modules blueprint:
```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: name
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: topics
            field:
              mode: default
              resource: topic
              create: true
              reorderable: true
              type: has_many
              display: Topics
              icon: has_many
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              order_column: module_topic.sort_order
title: Modules
```

Topics blueprint:
```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: name
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: slides
            field:
              mode: default
              resource: slide
              create: true
              reorderable: true
              order_column: sort_order
              type: has_many
              display: Slides
              icon: has_many
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
title: Topic
```
