### ISSUE TITLE
DoubleThreeDigital\Runway\Fieldtypes\BaseFieldtype::makeTitle():

### ISSUE THREAD

**Issue by freshface** [duncanmcclean/runway#342]
### Description

I have a many to many relation (users and events)
If i want to link users an event i get this error:

```DoubleThreeDigital\Runway\Fieldtypes\BaseFieldtype::makeTitle():```

If u cast user to json or array the error is gone.

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use DoubleThreeDigital\Runway\Traits\HasRunwayResource;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Event extends Model
{
    use HasFactory, HasRunwayResource;
    protected $table = 'events';
    protected $guarded = [];

    protected $casts = [
        'users' => 'json',
    ];



    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'event_user', 'event_id', 'users_id');
    }

}
```

But then the linked user or not stored in the database or shown in the UI.

### Steps to reproduce

Event model

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use DoubleThreeDigital\Runway\Traits\HasRunwayResource;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Event extends Model
{
    use HasFactory, HasRunwayResource;
    protected $table = 'events';
    protected $guarded = [];

    protected $casts = [
        'users' => 'json',
    ];



    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'event_user', 'event_id', 'users_id');
    }

}
```

Users model

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use DoubleThreeDigital\Runway\Traits\HasRunwayResource;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Casts\AsArrayObject;

class Users extends Model
{
    use HasFactory, HasRunwayResource;
    protected $table = 'users';
    protected $guarded = [];

    protected $casts = [
        'email' => 'string',
        'name' => 'string',
        // 'events' => AsArrayObject::class,
    ];


    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function events()
    {
        return $this->BelongsToMany(Event::class, 'event_user');
    }

}
```

Runway config

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Resources
    |--------------------------------------------------------------------------
    |
    | Configure the resources (models) you'd like to be available in Runway.
    |
    */

    'resources' => [

        \App\Models\Client::class => [
            'name' => 'Clients',
            'blueprint' => 'client',
        ],
        \App\Models\Notes::class => [
            'name' => 'Notes',
            'blueprint' => 'note',
        ],
        \App\Models\Users::class => [
            'name' => 'Users',
            'blueprint' => 'users',
            'title_field' => 'email',
        ],
        \App\Models\Event::class => [
            'name' => 'Events',
            'blueprint' => 'events',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Disable Migrations?
    |--------------------------------------------------------------------------
    |
    | Should Runway's migrations be disabled?
    | (eg. not automatically run when you next vendor:publish)
    |
    */

    'disable_migrations' => false,

];
```

Users blueprint

```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: name
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: events
            field:
                mode: default
                resource: event
                display: 'Events'
                type: 'has_many'
          -
            handle: email
            field:
              type: text
              required: true
              validate:
                - required
title: 'Clients Statamic'
```

Events blueprint

```
title: Page
tabs:
  main:
    display: Main
    sections:
      -
        display: General
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              input_type: text
              localizable: true
              listable: true
              display: Title
              validate:
                - required
      -
        display: Hero
        fields:
          -
            import: hero
            prefix: hero_
      -
        display: 'Page builder'
        fields:
          -
            import: page_builder
  seo:
    display: SEO
    sections:
      -
        display: Basic
        instructions: 'Basic SEO settings.'
        fields:
          -
            import: 'statamic-peak-seo::seo_basic'
      -
        display: Advanced
        instructions: 'Advanced SEO settings.'
        fields:
          -
            import: 'statamic-peak-seo::seo_advanced'
      -
        display: 'Open Graph'
        instructions: 'Open Graph meta tags for social sharing.'
        fields:
          -
            import: 'statamic-peak-seo::seo_open_graph'
      -
        display: Sitemap
        instructions: 'Sitemap configuration.'
        fields:
          -
            import: 'statamic-peak-seo::seo_sitemap'
      -
        display: 'JSON-ld Schema'
        instructions: 'Custom JSON-ld schema objects.'
        fields:
          -
            import: 'statamic-peak-seo::seo_jsonld'
  sidebar:
    display: Sidebar
    sections:
      -
        display: Meta
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              generate: true
              listable: hidden
              display: Slug
              validate:
                - required
          -
            handle: date
            field:
              type: date
              listable: true
              required: true
              validate:
                - required
              display: Date
              mode: single
              time_enabled: false
              time_required: false
              earliest_date: '2021-01-01'
              full_width: false
              inline: false
              columns: 1
              rows: 1
          -
            handle: users
            field:
                mode: default
                resource: users
                display: 'users'
                type: 'has_many'
```

### Environment

Environment
Application Name: Statamic Peak
Laravel Version: 10.23.1
PHP Version: 8.1.23
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: sio.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
doublethreedigital/runway: 5.3.0
jonassiewertsen/statamic-livewire: 2.12.0
marcorieser/tailwind-merge-statamic: 0.2.0
rias/statamic-address-field: 1.1.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.5.2
studio1902/statamic-peak-seo: 7.0.2
studio1902/statamic-peak-tools: 3.2
