### ISSUE TITLE
Error on collection list view when blueprint has a `Has Many` field

### ISSUE THREAD

**Issue by kevnk** [duncanmcclean/runway#368]
### Description

Viewing the collection list view in CP is showing error "Call to a member function display() on null" when adding a `Has Many` field in the blueprint

Watch this: https://www.loom.com/share/8a1e036a534248efab5f62c71a32f504?sid=5ab94d76-e13a-4ccc-a890-b4c21fb377e2

### Steps to reproduce

1. Create a new collection without a Has Many field
2. Verify you can view the collection list page with no errors
3. Edit the collection's blueprint and add a Has Many field
4. Verify you see the error on the collection list page

### Environment

Environment
Application Name: Ref UL
Laravel Version: 10.29.0
PHP Version: 8.2.10
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: ref-ul.valet
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 PRO

Statamic Addons
doublethreedigital/runway: 5.4.1
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6.2
studio1902/statamic-peak-seo: 7.0.4
studio1902/statamic-peak-tools: 3.2

**Comment by duncanmcclean** [comment]
Hey 👋

Would you be able to provide your Runway config file (`config/runway.php`) and the blueprint for your books resource?

**Comment by kevnk** [comment]
**config/runway.php**
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Resources
    |--------------------------------------------------------------------------
    |
    | Configure the resources (models) you'd like to be available in Runway.
    |
    */

    'resources' => [
        \App\Models\Book::class => [
            'name' => 'Books',
            'blueprint' => 'book',
            'cp_icon' => 'book-pages',
            'route' => '/listen/{{ slug }}',
            'read_only' => true,
            'order_by' => 'title',
            'title_field' => 'title_with_authors',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Disable Migrations?
    |--------------------------------------------------------------------------
    |
    | Should Runway's migrations be disabled?
    | (eg. not automatically run when you next vendor:publish)
    |
    */

    'disable_migrations' => false,

];
```

Here's [the full stack trace](https://flareapp.io/share/pPvKExn7)

**Comment by duncanmcclean** [comment]
Are you able to provide the `book` blueprint too?

**Comment by kevnk** [comment]
**book blueprint**

```
tabs:
  main:
    display: Main
    sections:
      - fields:
          - handle: title
            field:
              type: text
              required: true
              validate:
                - required
          - handle: subtitle
            field:
              input_type: text
              antlers: false
              type: text
              display: Subtitle
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: description
            field:
              type: markdown
              localizable: true
              display: Description
              instructions_position: above
              listable: hidden
              visibility: visible
              automatic_line_breaks: true
              automatic_links: false
              escape_markup: false
              smartypants: false
              restrict: false
              antlers: false
              hide_display: false
          - handle: cover_image_url
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Cover Image Url'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
      - display: Contributors
        fields:
          - handle: authors
            field:
              mode: typeahead
              create: true
              collections:
                - authors
              type: entries
              display: Authors
              icon: entries
              width: 33
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: narrators
            field:
              mode: typeahead
              create: true
              collections:
                - narrators
              type: entries
              display: Narrators
              icon: entries
              width: 33
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: publishers
            field:
              mode: typeahead
              create: true
              collections:
                - publishers
              type: entries
              display: Publishers
              icon: entries
              width: 33
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
      - display: 'More Info'
        fields:
          - handle: tags
            field:
              mode: typeahead
              create: true
              taxonomies:
                - categories
              type: terms
              display: Categories
              icon: taxonomy
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: awards
            field:
              input_type: text
              antlers: false
              type: text
              display: Awards
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: is_abridged
            field:
              default: false
              type: toggle
              display: 'Is Abridged'
              icon: toggle
              width: 25
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: is_author_read
            field:
              default: false
              type: toggle
              display: 'Is Author Read'
              icon: toggle
              width: 25
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: is_bestseller
            field:
              default: false
              type: toggle
              display: 'Is Bestseller'
              icon: toggle
              width: 25
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: is_classic
            field:
              default: false
              type: toggle
              display: 'Is Classic'
              icon: toggle
              width: 25
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      - fields:
          - handle: book_id
            field:
              input_type: number
              antlers: false
              type: text
              display: 'Book ID'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: slug
            field:
              type: slug
              localizable: true
          - handle: release_date
            field:
              mode: single
              inline: false
              full_width: false
              columns: 1
              rows: 1
              time_enabled: false
              time_seconds_enabled: false
              type: date
              display: 'Release Date'
              icon: date
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: runtime
            field:
              input_type: number
              antlers: false
              type: text
              display: Runtime
              icon: text
              instructions: 'In seconds'
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: isbn
            field:
              input_type: text
              antlers: false
              type: text
              display: ISBN
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: product_type
            field:
              options:
                Audiobook: null
                Podcast: null
                Course: null
                Other: null
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              default: Audiobook
              type: select
              display: 'Product Type'
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: language
            field:
              options:
                English: null
                French: null
                Spanish: null
                Other: null
              taggable: true
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              default: English
              type: select
              display: Language
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: digital_listing_price
            field:
              input_type: number
              antlers: false
              type: text
              display: DLP
              icon: text
              instructions: 'Use cents instead of dollars with a decimal. For example, use `999` for a DLP of `$9.99`'
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          - handle: updated_at
            field:
              mode: single
              inline: false
              full_width: false
              columns: 1
              rows: 1
              time_enabled: false
              time_seconds_enabled: false
              type: date
              display: 'Updated At'
              icon: date
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
title: Book
```
