### ISSUE TITLE
Unique validation not working on update

### ISSUE THREAD

**Issue by saqueib** [duncanmcclean/runway#385]
### Description

Unable to validate unique email using laravel unique rule, it works fine for **creating** but **update** always gives 
`This value has already been taken.`

**Blueprint**
```yaml
-
  handle: email
  field:
    type: text
    display: Email
    validate:
      - required
      - email
      - unique:users,email,{id}
```

### Steps to reproduce

1. add a unique validation rule on a field 
```
    display: Email
    validate:
      - required
      - unique:users,email,{id}
```

2. Create an entry it should work
3. Open created entry and try saving again, you will see 
`This value has already been taken.`

### Environment

```
Environment
Application Name: CMS
Laravel Version: 10.15.0
PHP Version: 8.2.8
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Livewire
Livewire: v3.0.5

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Disabled
Static Caching: full
Version: 4.39.0 PRO

Statamic Addons
doublethreedigital/runway: 5.5.2
markkravchuk/statamic-activity-book: 1.0.1
rias/statamic-data-import: 1.3.0
```
